### ISSUE TITLE
Replace Deprecated Commands module with Subprocess

### ISSUE THREAD

**Issue by jaredthecoder** [hatRiot/zarp#20]
According to the official Python documentation, commands (https://docs.python.org/2/library/commands.html) has been deprecated since Python 2.6 and is not included in Python 3.x. Therefore, I think it may be helpful to replace commands with the newer functionality.

I will make a pull request with the changes if this is something that you find okay, hatRiot.

**Comment by hatRiot** [comment]
Zarp currently requires 2.6 to run, but I agree it should be wiped from the code base.  I'll accept a PR of this if it's something you'd like to take on!  I don't think there are too many instances of it around.

**Comment by godeyes333** [comment]
root@localhost:~/zarp# sudo python zarp.py
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
[!] IPv4 forwarding disabled.  Enabling..
[-] Error enabling IPv4 forwarding.

**Comment by OBITORASU** [comment]
Sorry for the bump but are you still accepting PRs for this enhancement?

**Comment by hatRiot** [comment]
sure

**Comment by hatRiot** [comment]
Thanks @OBITORASU !
