### ISSUE TITLE
MAC OSX 

### ISSUE THREAD

**Issue by hktalent** [hatRiot/zarp#27]
sudo python2 ./zarp.py
[-] Module src.modules.attacks.beef_hook failed to load! (No module named netlib)
[-] Module src.modules.attacks.pemod failed to load! (No module named netlib)
[-] Module src.modules.attacks.replacer failed to load! (No module named netlib)
[!] Loaded 33 modules.
     ____   __   ____  ____
    (__  ) / _\ (  _ (  _ '
     / _/ /    \ )   / ) __/
    (____)_/_/(**_)(**)  [Version: 0.1.8]

```
[1] Poisoners       [5] Parameter
[2] DoS Attacks     [6] Services 
[3] Sniffers        [7] Attacks  
[4] Scanners        [8] Sessions 
```

**Comment by bwall** [comment]
OSX!!!!
