### ISSUE TITLE
MAC OSX 10.11.6

### ISSUE THREAD

**Issue by hktalent** [hatRiot/zarp#28]
sudo python2 ./zarp.py
[-] Module src.modules.attacks.beef_hook failed to load! (No module named netlib)
[-] Module src.modules.attacks.pemod failed to load! (No module named netlib)
[-] Module src.modules.attacks.replacer failed to load! (No module named netlib)
[!] Loaded 33 modules.
     ____   __   ____  ____
    (__  ) / _\ (  _ (  _ '
     / _/ /    \ )   / ) __/
    (____)_/_/(**_)(**)  [Version: 0.1.8]

```
[1] Poisoners       [5] Parameter
[2] DoS Attacks     [6] Services 
[3] Sniffers        [7] Attacks  
[4] Scanners        [8] Sessions 
```

**Comment by hktalent** [comment]
sudo python ~/pip2.py  install  --ignore-installed --trusted-host pypi.douban.com  -i http://pypi.douban.com/simple netlib
The directory '/Users/xiatian/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/xiatian/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting netlib
  Downloading http://pypi.doubanio.com/packages/7e/24/d23f45d1168f579c89d970087eb39f2b1bc2176c2bfdf46cb296157af6b5/netlib-0.17-py2.py3-none-any.whl
Collecting mitmproxy>=0.17 (from netlib)
  Downloading http://pypi.doubanio.com/packages/3d/dc/87548a9cb2c62db525444f9ae2a70ff4f9b1bc0a94fcc789483c2355fb61/mitmproxy-0.17-py2-none-any.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 216kB/s 
Collecting tornado<4.4,>=4.3 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/21/29/e64c97013e97d42d93b3d5997234a6f17455f3744847a7c16289289f8fa6/tornado-4.3.tar.gz (450kB)
    100% |████████████████████████████████| 460kB 2.9MB/s 
Collecting html2text<=2016.4.2,>=2016.1.8 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/85/5f/d57f91075dfb29677bcbe29376b3ed7db361db35a091b5990dca14c63681/html2text-2016.4.2.tar.gz (45kB)
    100% |████████████████████████████████| 51kB 2.2MB/s 
Collecting Pillow<3.3,>=3.2 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/13/68/c5c7b7518e27e2b74e6a90b057514ded588dbce654548594205e7a7d36ed/Pillow-3.2.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.0MB)
    100% |████████████████████████████████| 3.0MB 186kB/s 
Collecting hyperframe<4.0,>=3.2.0 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/d8/89/44ff46f15dba53a8c16cb8cab89ecb1e44f8aa211628b43d341004cfcf7a/hyperframe-3.2.0-py2.py3-none-any.whl
Collecting hpack<3.0,>=2.1.0 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/c0/df/2c35ce4aa80c5741f894532beed35ce521491164e3aca235890148f38304/hpack-2.3.0-py2.py3-none-any.whl
Collecting cryptography<1.4,>=1.3 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/31/48/60132b1e917d7d18894e4357ccedee055bc8919821626132ba56e0702a02/cryptography-1.3.4-cp27-cp27m-macosx_10_10_intel.whl (2.4MB)
    100% |████████████████████████████████| 2.4MB 343kB/s 
Collecting configargparse<0.11,>=0.10 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/d0/b8/8f7689980caa66fc02671f5837dc761e4c7a47c6ca31b3e38b304cbc3e73/ConfigArgParse-0.10.0.tar.gz
Collecting lxml<3.7,>=3.5.0 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/4f/3f/cf6daac551fc36cddafa1a71ed48ea5fd642e5feabd3a0d83b8c3dfd0cb4/lxml-3.6.4.tar.gz (3.7MB)
    100% |████████████████████████████████| 3.7MB 508kB/s 
Collecting construct<2.6,>=2.5.2 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/14/d7/f94299cc597f74c558907aa76c635966b029d5c58d8cda7ecc4035fb8ab4/construct-2.5.2-py2.py3-none-any.whl (72kB)
    100% |████████████████████████████████| 81kB 1.5MB/s 
Collecting Flask<0.11,>=0.10.1 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/db/9c/149ba60c47d107f85fe52564133348458f093dd5e6b57a5b60ab9ac517bb/Flask-0.10.1.tar.gz (544kB)
    100% |████████████████████████████████| 552kB 1.9MB/s 
Collecting pyasn1<0.2,>=0.1.9 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/69/be/e8946f7867b84b0e61a613f6fd56f63266190b1a470f945178f7cbc4d0ae/pyasn1-0.1.9-py2.py3-none-any.whl
Collecting pyOpenSSL<17.0,>=16.0 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/b1/4e/54c8995d2de887919272c2b711cd430277ec33e0f7bb88cb564244c102b6/pyOpenSSL-16.0.0-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 2.2MB/s 
Collecting blinker<1.5,>=1.4 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/1b/51/e2a9f3b757eb802f61dc1f2b09c8c99f6eb01cf06416c0671253536517b6/blinker-1.4.tar.gz (111kB)
    100% |████████████████████████████████| 112kB 2.1MB/s 
Collecting passlib<1.7,>=1.6.5 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/2d/a7/1a3363e5d531d438267a79d43d4b8d224655adef489e98fc96678fe16ed1/passlib-1.6.5-py2.py3-none-any.whl (317kB)
    100% |████████████████████████████████| 327kB 5.0MB/s 
Collecting backports.ssl-match-hostname<3.6,>=3.5.0.1 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/76/21/2dc61178a2038a5cb35d14b61467c6ac632791ed05131dda72c20e7b9e23/backports.ssl_match_hostname-3.5.0.1.tar.gz
Collecting certifi>=2015.11.20.1 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/dd/ed/e9bf6a9dc79e23c68385c4ea692f0e9e1a7880518872564f88be013b552f/certifi-2016.8.8-py2.py3-none-any.whl (384kB)
    100% |████████████████████████████████| 389kB 372kB/s 
Collecting ipaddress<1.1,>=1.0.15; python_version == "2.7" (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/23/6a/813ac29a01e4c33c19c2bded98ac3d4266ebbf0bd2c0eb0020e1c969958d/ipaddress-1.0.16-py27-none-any.whl
Collecting pyperclip<1.6,>=1.5.22 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/7b/a5/48eaa1f2d77f900679e9759d2c9ab44895e66e9612f7f6b5333273b68f29/pyperclip-1.5.27.zip
Collecting urwid<1.4,>=1.3.1 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/85/5d/9317d75b7488c335b86bd9559ca03a2a023ed3413d0e8bfe18bea76f24be/urwid-1.3.1.tar.gz (588kB)
    100% |████████████████████████████████| 593kB 368kB/s 
Collecting h2<3.0,>=2.1.2 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/48/45/13fb1990f552fcff08003ee1b2e1d3c13bfb616f5c12bd0ddd77a568a95e/h2-2.4.0-py2.py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 280kB/s 
Collecting requests<2.10,>=2.9.1 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/8b/e7/229a428b8eb9a7f925ef16ff09ab25856efe789410d661f10157919f2ae2/requests-2.9.2-py2.py3-none-any.whl (502kB)
    100% |████████████████████████████████| 512kB 234kB/s 
Collecting enum34<2,>=1.0.4; python_version == "2.7" (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting watchdog<0.9,>=0.8.3 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/54/7d/c7c0ad1e32b9f132075967fc353a244eb2b375a3d2f5b0ce612fd96e107e/watchdog-0.8.3.tar.gz (83kB)
    100% |████████████████████████████████| 92kB 1.2MB/s 
Collecting pyparsing<2.2,>=2.1 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/85/b9/188515f35f78533b3f82966a2c3f1a71a86df8b801367ee75a77191a861d/pyparsing-2.1.8-py2.py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 769kB/s 
Collecting click<7.0,>=6.2 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/7a/00/c14926d8232b36b08218067bcd5853caefb4737cda3f0a47437151344792/click-6.6.tar.gz (283kB)
    100% |████████████████████████████████| 286kB 1.9MB/s 
Collecting six<1.11,>=1.10 (from mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/c8/0a/b6723e1bc4c516cb687841499455a8505b44607ab535be01091c0f24f079/six-1.10.0-py2.py3-none-any.whl
Collecting singledispatch (from tornado<4.4,>=4.3->mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/c5/10/369f50bcd4621b263927b0a1519987a04383d4a98fb10438042ad410cf88/singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting backports_abc>=0.4 (from tornado<4.4,>=4.3->mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/f5/5e/57e1afdc63d8c37496b2f6d9cb0ddfc4a3d55c949074debeab7594c19b54/backports_abc-0.4-py2.py3-none-any.whl
Collecting idna>=2.0 (from cryptography<1.4,>=1.3->mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/71/02/dee75fc3e6f7455bf69221164f94586ee13552c5f33c8002335667a3d122/idna-2.1-py2.py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 2.9MB/s 
Collecting cffi>=1.4.1 (from cryptography<1.4,>=1.3->mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/6e/63/f240a2c4b2b8e40c8d94df8d4a634c453670c4632caacdf32e9ef20a6c95/cffi-1.7.0-cp27-cp27m-macosx_10_10_intel.whl (212kB)
    100% |████████████████████████████████| 215kB 1.6MB/s 
Collecting setuptools>=11.3 (from cryptography<1.4,>=1.3->mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/07/1a/19b5d2de13e1c300f703e7914031fe5fe449d19e0ded5a34db9f3e7969ff/setuptools-26.0.0-py2.py3-none-any.whl (459kB)
    100% |████████████████████████████████| 460kB 224kB/s 
Collecting Werkzeug>=0.7 (from Flask<0.11,>=0.10.1->mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/f7/41/6847fed02f9c1692461f66d2b9391c1e4236451f0cb5bcbe3ebc73de1ca2/Werkzeug-0.11.10-py2.py3-none-any.whl (306kB)
    100% |████████████████████████████████| 307kB 359kB/s 
Collecting Jinja2>=2.4 (from Flask<0.11,>=0.10.1->mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/96/a1/c56bc4d99dc2663514a8481511e80eba8994133ae75eebdadfc91a5597d9/Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |████████████████████████████████| 266kB 370kB/s 
Collecting itsdangerous>=0.21 (from Flask<0.11,>=0.10.1->mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/dc/b4/a60bcdba945c00f6d608d8975131ab3f25b22f2bcfe1dab221165194b2d4/itsdangerous-0.24.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 1.7MB/s 
Collecting PyYAML>=3.10 (from watchdog<0.9,>=0.8.3->mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/04/60/abfb3a665ee0569b60c89148b7187ddd8a36cb65e254fba945ae1315645d/PyYAML-3.11.zip (371kB)
    100% |████████████████████████████████| 378kB 2.8MB/s 
Collecting argh>=0.24.1 (from watchdog<0.9,>=0.8.3->mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/06/1c/e667a7126f0b84aaa1c56844337bf0ac12445d1beb9c8a6199a7314944bf/argh-0.26.2-py2.py3-none-any.whl
Collecting pathtools>=0.1.1 (from watchdog<0.9,>=0.8.3->mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/e7/7f/470d6fcdf23f9f3518f6b0b76be9df16dcc8630ad409947f8be2eb0ed13a/pathtools-0.1.2.tar.gz
Collecting pycparser (from cffi>=1.4.1->cryptography<1.4,>=1.3->mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/6d/31/666614af3db0acf377876d48688c5d334b6e493b96d21aa7d332169bee50/pycparser-2.14.tar.gz (223kB)
    100% |████████████████████████████████| 225kB 444kB/s 
Collecting MarkupSafe (from Jinja2>=2.4->Flask<0.11,>=0.10.1->mitmproxy>=0.17->netlib)
  Downloading http://pypi.doubanio.com/packages/c0/41/bae1254e0396c0cc8cf1751cb7d9afc90a602353695af5952530482c963f/MarkupSafe-0.23.tar.gz
Installing collected packages: backports.ssl-match-hostname, six, singledispatch, certifi, backports-abc, tornado, html2text, Pillow, hyperframe, hpack, idna, pycparser, cffi, pyasn1, setuptools, enum34, ipaddress, cryptography, configargparse, lxml, construct, Werkzeug, MarkupSafe, Jinja2, itsdangerous, Flask, pyOpenSSL, blinker, passlib, pyperclip, urwid, h2, requests, PyYAML, argh, pathtools, watchdog, pyparsing, click, mitmproxy, netlib
  Running setup.py install for backports.ssl-match-hostname ... done
  Running setup.py install for tornado ... done
  Running setup.py install for html2text ... done
  Running setup.py install for pycparser ... done
  Running setup.py install for configargparse ... done
  Running setup.py install for lxml ... done
  Running setup.py install for MarkupSafe ... done
  Running setup.py install for itsdangerous ... done
  Running setup.py install for Flask ... done
  Running setup.py install for blinker ... done
  Running setup.py install for pyperclip ... done
  Running setup.py install for urwid ... done
  Running setup.py install for PyYAML ... done
  Running setup.py install for pathtools ... done
  Running setup.py install for watchdog ... done
  Running setup.py install for click ... done
Successfully installed Flask-0.10.1 Jinja2-2.8 MarkupSafe-0.23 Pillow-3.2.0 PyYAML-3.11 Werkzeug-0.11.10 argh-0.26.2 backports-abc-0.4 backports.ssl-match-hostname-3.5.0.1 blinker-1.4 certifi-2016.8.2 cffi-1.7.0 click-6.6 configargparse-0.10.0 construct-2.5.2 cryptography-1.3.4 enum34-1.1.6 h2-2.4.0 hpack-2.3.0 html2text-2016.4.2 hyperframe-3.2.0 idna-2.1 ipaddress-1.0.16 itsdangerous-0.24 lxml-3.6.1 mitmproxy-0.17 netlib-0.11.1 passlib-1.6.5 pathtools-0.1.2 pyOpenSSL-0.13.1 pyasn1-0.1.9 pycparser-2.14 pyparsing-2.1.5 pyperclip-1.5.27 requests-2.10.0 setuptools-25.1.3 singledispatch-3.4.0.3 six-1.10.0 tornado-4.3 urwid-1.3.1 watchdog-0.8.3

but the same
[-] Module src.modules.attacks.beef_hook failed to load! (No module named netlib)
[-] Module src.modules.attacks.pemod failed to load! (No module named netlib)
[-] Module src.modules.attacks.replacer failed to load! (No module named netlib

**Comment by hatRiot** [comment]
I unfortunately don't have an OSX to test on, but it could be an updated dependency conflict.  I'll look into it.

**Comment by bwall** [comment]
OSX!!!!
