### ISSUE TITLE
OSX

### ISSUE THREAD

**Issue by bwall** [hatRiot/zarp#29]
OSX!!!!!!!!!!!!

**Comment by bwall** [comment]
What commits are related to resolving this issue?  Or are you being super irresponsible and just closing tickets at random? ;)

**Comment by hatRiot** [comment]
[DUPLICATE](https://github.com/hatRiot/zarp/issues/28) [ISSUE](https://github.com/hatRiot/zarp/issues/25)[!](https://github.com/hatRiot/zarp/issues/27)

**Comment by bwall** [comment]
STOP OPPRESSING MY PEOPLE!
