### ISSUE TITLE
zarp broken by pyOpenSSL and netlib

### ISSUE THREAD

**Issue by NeolithEra** [hatRiot/zarp#35]
Hi, users are unable to run **_zarp_** due to dependency conflict with _**pyOpenSSL**_ package. 
As shown in the following full dependency graph of **_zarp_**, **_zarp_** requires _**pyOpenSSL==0.13.1**_，while **_netlib==0.11.1_** requires _**pyOpenSSL>=0.14**_.

According to pip’s _**“first found wins”**_ installation strategy, _**pyOpenSSL==0.13.1**_ is the actually installed version. 
However, _**pyOpenSSL==0.13.1**_ does not satisfy _**pyOpenSSL>=0.14**_.

### Dependency tree
```
zarp-0.1.8
| +-flask(version range:==0.10.1)
| | +-itsdangerous(version range:>=0.21)
| | +-jinja2(version range:>=2.4)
| | | +-markupsafe(version range:>=0.23)
| | +-werkzeug(version range:>=0.7)
| +-netlib(version range:==0.11.1)
| | +-passlib(version range:>=1.6.2)
| | +-pyasn1(version range:>=0.1.7)
| | +-pyopenssl(version range:>=0.14)
| +-paramiko(version range:==1.15.2)
| +-pyopenssl(version range:==0.13.1)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution

1.	Fix your direct dependency to be pyOpenSSL>=0.14.

2.	Fix your direct dependency to be pyOpenSSL==0.14. 

3.	Remove your direct dependency pyOpenSSL, and use pyOpenSSL transitively introduced by netlib.

I have checked the above revisions will not affect your downstream projects now.
Which solution do you prefer, 1, 2 or 3?
@hatRiot  Please let me know your choice. I can submit a PR to solve this issue.

**Comment by hatRiot** [comment]
Thanks for the detailed issue. I think option #3 is preferred; a PR would be great too!
