### ISSUE TITLE
Host appears to still be up

### ISSUE THREAD

**Issue by Bobowonnell** [hatRiot/zarp#38]
Whenever I try to preform a LAND DoS attack I get a message saying host appears to still be up.Can I get a further explanation on this plz. Thanks in advance!

**Comment by hatRiot** [comment]
LAND has been patched for many moons, no modern Windows machine will be vulnerable to this.

https://insecure.org/sploits/land.ip.DOS.html

**Comment by Bobowonnell** [comment]
Does this also apply to Nestea DoS?

**Comment by Bobowonnell** [comment]
Well really do any DoS attacks work rn?
